stages:
  - e2e

.e2e: &e2e
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.30.0-focal
  script:
    - sh ./.ci.sh
  artifacts:
    when: always
    paths:
      - ./playwright-report/
      - ./test-results/

api-tests:
  <<: *e2e
  variables:
    CONFIG: "api"
    TAG: api

functional-tests:chrome:
  <<: *e2e
  variables:
    CONFIG: "functional"
    TAG: functional
    BROWSER: "chrome"

functional-tests:edge:
  <<: *e2e
  variables:
    CONFIG: "functional"
    TAG: functional
    BROWSER: "msedge"

functional-tests:firefox:
  <<: *e2e
  variables:
    CONFIG: "functional"
    TAG: functional
    BROWSER: "firefox"