e2e tests:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.30.0-focal
  script:
    - npm ci
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/