stages:
  - e2e

.e2e: &e2e
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.35.1
  script:
    - sh ./.ci.sh
  artifacts:
    when: always
    paths:
      - ./playwright-report/
      - ./test-results/

prod-api-tests:
  <<: *e2e
  variables:
    BASE_URL: $PROD
    PROJECT: api

prod-functional-tests:chrome:
  <<: *e2e
  variables:
    BASE_URL: $PROD
    PROJECT: chrome

prod-functional-tests:edge:
  <<: *e2e
  variables:
    BASE_URL: $PROD
    PROJECT: msedge

prod-functional-tests:firefox:
  <<: *e2e
  variables:
    BASE_URL: $PROD
    PROJECT: firefox