stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.30.0-focal
  script:
    - npm ci
    - npx playwright install chrome
    - npx playwright install msedge
    - npx playwright test tests/Functional.spec.ts --config=functional-tests.config.ts
    - npx playwright test tests/API.spec.ts --config=api-tests.config.ts
  artifacts:
    when: always
    paths:
      - /builds/alexeitsarenkov/playwright/playwright-report/
      - /builds/alexeitsarenkov/playwright/test-results/
      - /builds/alexeitsarenkov/playwright/**/*-snapshots