version: '3.8'

services:
  playwright-tests:
    environment:
      - BASE_URL=${BASE_URL}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - KEY=${KEY}
      - TOKEN=${TOKEN}
    build: .
    command: npx playwright test --workers=1 --retries=1
    volumes:
      - ./playwright-report:/playwright/playwright-report