version: '3.8'

services:
  playwright:
    image: playwright
    environment:
      - BASE_URL=${BASE_URL}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - KEY=${KEY}
      - TOKEN=${TOKEN}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test --workers=1
    volumes:
      - ./playwright-report/:/playwright/playwright-report